a = int(input("Enter the first number : "))
b = int(input("Enter the second number : "))
print("\n\t\tRESULTS")
print("Sum of the given two numbers is : ",(a+b))
print("Difference of the given two numbers is : ",abs(a-b))
print("Product of the given two numbers is : ",(a*b))
print("Fractional Quotient of the divison of given two numbers is : ",(a/b))
print("Integer Quotient of the divison of given two numbers is : ",(a//b))
print("Remainder of the divison of given two numbers is : ",(a%b))